### ISSUE TITLE
Command 'singularity' not found

### ISSUE THREAD

**Issue by zhaotianjing** [comorment/mixer#10]
Hi,

I try to use the mixer on the HPC, and I followed instructions [here](https://github.com/comorment/containers#getting-started) to clone the "containers" repository.

Then I started to run the example for simulated data [here](https://github.com/comorment/mixer/blob/main/usecases/mixer_simu.md). But I got an error when I run the first line: `singularity shell --home $PWD:/home $SIF/mixer.sif `. The error is 
```
Command 'singularity' not found, but can be installed with:
apt install singularity
```
May I know how I can fix it?

Thanks,
Tianjing

**Comment by espenhgn** [comment]
Hi. You need singularity (https://sylabs.io/singularity/) or apptainer (https://apptainer.org) software. 
You need to refer to your HPC's documentation on how to get either; often such software can be loaded issuing in the terminal:
```
module spider singularity  # search
...
module load singularity/3.7.3  # load some version
singularity run ....
```
