### ISSUE TITLE
feature request: add the image to dockerhub

### ISSUE THREAD

**Issue by cmatKhan** [comorment/mixer#13]
This is just a feature request, but it would be a nice:

I see that the image is being built by Docker, and then a `sif` is being provided in this repo.

As an alternative: you can push the docker image up to dockerhub. Singularity can pull docker images from docker hub and build the `.sif`. For example, the command would look like:

`singularity pull <your username>/<your image name>`

Admittedly, it is quicker to pull the git repo than it is to use that -- singularity has to build the image, not just download it. but, it is also convenient, since it gives the user the option of using either docker or singularity, and the instructions for pulling the image are very simple

**Comment by espenhgn** [comment]
Thanks for the heads up, @cmatKhan! I agree it is worth investigating this option, at least for those who do not work on systems that are otherwise without an internet connection.

**Comment by espenhgn** [comment]
Hi again @cmatKhan. To resurrect this thread; I'm now setting up and pushing Docker images and Singularity containers onto [GHCR.io](https://github.com/comorment/mixer/pkgs/container/mixer). 

It should now (and in the future) be possible to obtain the container by either issuing:
```
docker pull ghcr.io/comorment/mixer:<version> # or 
apptainer pull ghcr.io/comorment/mixer:<version> # or
singularity pull ghcr.io/comorment/mixer:<version> # or
oras pull ghcr.io/comorment/mixer:<version>
```
where `<version>` would be either `main`, `latest`, `sha_<GIT SHA>`, `v<major>.<minor>.<patch>` as listed on the [packages page](https://github.com/comorment/mixer/pkgs/container/mixer). 
The latter statement relies on the [ORAS CLI](https://oras.land) that may be installed easily in e.g., a conda environment, and downloads the cloud-built .sif file.

This is still on a feature branch, as I haven't done any proper testing yet with these builds.

**Comment by cmatKhan** [comment]
Thank you!

But, I think if I were making this feature request today, I'd say that it would be nice if mixer was added to bioconda -- that way it is automatically added to [biocontainers](https://biocontainers.pro/), where docker and singularity images are built automatically

**Comment by espenhgn** [comment]
Adding this project (or rather the main mixer developer [repo](https://github.com/precimed/mixer)) to biocontainers may be  something for the future. The GitHub container registry will be our main solution for distribution I believe, as we tend to add multiple tools into the builds. My impression is that biocontainers is mainly for singular tools (but I haven't used it at all).
