### ISSUE TITLE
Singularity version

### ISSUE THREAD

**Issue by mvacher** [comorment/mixer#26]
Hi,

I've tried different versions of Singularity but cannot find one that matches the format of the provided .sif file.

Could please provide the version with which the image was generated ?

Thank you

```
$ singularity --version
singularity version 3.8.7
$ singularity exec --no-home mixer.sif python3 mixer.py ld --help
FATAL:   could not open image /home/vac007/junk/mixer/singularity/mixer.sif: image format not recognized

$ singularity --version
singularity version 3.7.3
$ singularity exec --no-home mixer.sif python3 mixer.py ld --help
FATAL:   could not open image /home/vac007/junk/mixer/singularity/mixer.sif: image format not recognized

$ singularity --version
2.6.1-dist
$ singularity exec --no-home mixer.sif python3 mixer.py ld --help
ERROR  : Unknown image format/type: hello.sif
ABORT  : Retval = 255
```

**Comment by espenhgn** [comment]
Hi @mvacher, 
Singularity >= 3.* should work (but not earlier versions), however, you may have gotten the git LFS pointer file(s), not the "large" files themselves. Try e.g., `head mixer.sif`. 

See https://git-lfs.com for installing the git LFS extension, then
```
cd </path/to/>mixer
git lfs install
git pull
```
ought to update the pointer files.
